notifications:
  webhooks:
    - https://webhook.commit-email.info/
dist: xenial
language: cpp
matrix:
  include:
    - name: MySQL system
      env:
        - MYSQL_VERSION=mysql-system
    - name: MySQL 5.7
      env:
        - MYSQL_VERSION=mysql-5.7
    - name: MySQL 8.0
      env:
        - MYSQL_VERSION=mysql-8.0
    - name: MariaDB 10.1
      env:
        - MYSQL_VERSION=mariadb-10.1.44
        - MROONGA_BUNDLED=yes
    - name: MariaDB 10.2
      env:
        - MYSQL_VERSION=mariadb-10.2.31
        - MROONGA_BUNDLED=yes
    - name: MariaDB 10.2 binary protocol
      env:
        - MYSQL_VERSION=mariadb-10.2.31
        - MROONGA_BUNDLED=yes
        - MROONGA_TEST_PS_PROTOCOL=yes
    - name: MariaDB 10.3
      env:
        - MYSQL_VERSION=mariadb-10.3.22
        - MROONGA_BUNDLED=yes
    - name: MariaDB 10.3 binary protocol
      env:
        - MYSQL_VERSION=mariadb-10.3.22
        - MROONGA_BUNDLED=yes
        - MROONGA_TEST_PS_PROTOCOL=yes
    - name: MariaDB 10.4
      env:
        - MYSQL_VERSION=mariadb-10.4.12
        - MROONGA_BUNDLED=yes
    - name: MariaDB 10.4 binary protocol
      env:
        - MYSQL_VERSION=mariadb-10.4.12
        - MROONGA_BUNDLED=yes
        - MROONGA_TEST_PS_PROTOCOL=yes
    - name: MariaDB 10.5
      env:
        - MYSQL_VERSION=mariadb-10.5.4
        - MROONGA_BUNDLED=yes
    - name: MariaDB 10.5 binary protocol
      env:
        - MYSQL_VERSION=mariadb-10.5.4
        - MROONGA_BUNDLED=yes
        - MROONGA_TEST_PS_PROTOCOL=yes
    - name: Percona Server 5.6
      env:
        - MYSQL_VERSION=percona-server-5.6
    - name: Percona Server 5.7
      env:
        - MYSQL_VERSION=percona-server-5.7
    - name: Percona Server 8.0
      env:
        - MYSQL_VERSION=percona-server-8.0
install:
  - tools/travis/install.sh
before_script:
  - tools/travis/before_script.sh
script:
  - travis_wait 40 tools/travis/script.sh
