notifications:
  webhooks:
    - https://webhook.commit-email.info/
dist: xenial
language: cpp
matrix:
  include:
    - env:
        - MYSQL_VERSION=mysql-system
    - env:
        - MYSQL_VERSION=mysql-5.7
    - env:
        - MYSQL_VERSION=mysql-8.0
    - env:
        - MYSQL_VERSION=mariadb-10.0.38
        - MROONGA_BUNDLED=yes
    - env:
        - MYSQL_VERSION=mariadb-10.0.38
        - MROONGA_BUNDLED=yes
        - MROONGA_TEST_EMBEDDED=yes
    - env:
        - MYSQL_VERSION=mariadb-10.1.41
        - MROONGA_BUNDLED=yes
    - env:
        - MYSQL_VERSION=mariadb-10.2.26
        - MROONGA_BUNDLED=yes
    - env:
        - MYSQL_VERSION=mariadb-10.2.26
        - MROONGA_BUNDLED=yes
        - MROONGA_TEST_PS_PROTOCOL=yes
    - env:
        - MYSQL_VERSION=mariadb-10.3.17
        - MROONGA_BUNDLED=yes
    - env:
        - MYSQL_VERSION=mariadb-10.3.17
        - MROONGA_BUNDLED=yes
        - MROONGA_TEST_PS_PROTOCOL=yes
    - env:
        - MYSQL_VERSION=percona-server-5.6
    - env:
        - MYSQL_VERSION=percona-server-5.7
install:
  - tools/travis/install.sh
before_script:
  - tools/travis/before_script.sh
script:
  - travis_wait 40 tools/travis/script.sh
