name: Package
on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: |
        0 0 * * *
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os:
          - debian-stretch
          - debian-stretch-i386
          - debian-buster
          - debian-buster-i386
          - centos-6
          - centos-7
          - centos-8
        package:
          - mariadb-server-10.1
          - mariadb-server-10.2
          - mariadb-server-10.3
          - mariadb-server-10.4
          - mysql-server-5.6
          - mysql-server-5.7
        exclude:
          - os: debian-buster
            package: mariadb-server-10.1
          - os: debian-buster-i386
            package: mariadb-server-10.1
          - os: centos-8
            package: mariadb-server-10.1
          - os: debian-stretch
            package: mariadb-server-10.2
          - os: debian-stretch-i386
            package: mariadb-server-10.2
          - os: debian-buster
            package: mariadb-server-10.2
          - os: debian-buster-i386
            package: mariadb-server-10.2
          - os: centos-8
            package: mariadb-server-10.2
          - os: debian-stretch
            package: mariadb-server-10.3
          - os: debian-stretch-i386
            package: mariadb-server-10.3
          - os: centos-6
            package: mariadb-server-10.3
          - os: debian-buster
            package: mariadb-server-10.4
          - os: debian-buster-i386
            package: mariadb-server-10.4
          - os: debian-stretch
            package: mariadb-server-10.4
          - os: debian-stretch-i386
            package: mariadb-server-10.4
          - os: centos-6
            package: mariadb-server-10.4
          - os: debian-buster
            package: mysql-server-5.6
          - os: debian-buster-i386
            package: mysql-server-5.6
          - os: debian-stretch
            package: mysql-server-5.6
          - os: debian-stretch-i386
            package: mysql-server-5.6
          - os: centos-8
            package: mysql-server-5.6
          - os: debian-buster
            package: mysql-server-5.7
          - os: debian-buster-i386
            package: mysql-server-5.7
          - os: debian-stretch
            package: mysql-server-5.7
          - os: debian-stretch-i386
            package: mysql-server-5.7
          - os: centos-8
            package: mysql-server-5.7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: |
          grep '^deb ' /etc/apt/sources.list | \
            sed -e 's/^deb /deb-src /' | \
            sudo tee /etc/apt/sources.list.d/source.list
          sudo apt update
          sudo apt -y -V install software-properties-common
          sudo add-apt-repository -y universe
          sudo add-apt-repository -y ppa:groonga/ppa
          sudo apt update
          sudo apt -y -V install \
            autoconf \
            gettext \
            groonga-normalizer-mysql \
            libgroonga-dev \
            libmysqld-dev \
            libtool \
            python3-pip \
            ruby
      - name: Install Sphinx
        run: |
          sudo pip3 install -v sphinx
      - name: Download MySQL source
        run: |
          mkdir -p ../mysql
          cd ../mysql
          apt source mysql-server
          ln -s $(find . -maxdepth 1 -type d | sort | tail -1) mysql
      - name: Clone dependencies
        run: |
          cd ..
          git clone --recursive https://github.com/groonga/groonga.git
          git clone --depth 1 https://github.com/clear-code/cutter.git
          git clone --depth 1 https://github.com/mroonga/mroonga.github.com.git
      - name: Generate configure
        run: |
          ./autogen.sh
      - name: Configure for archive
        run: |
          ./configure \
            --enable-document \
            --with-cutter-source-path=../cutter \
            --with-mroonga-github-com-path=../mroonga.github.com \
            --with-mysql-source=../mysql/mysql
      - name: Build archive
        run: |
          make dist
      - name: Update version
        run: |
          make update-latest-release \
            OLD_RELEASE=$(cat version) \
            OLD_RELEASE_DATE=$(date +%Y-%m-%d) \
            NEW_RELEASE_DATE=$(date +%Y-%m-%d)
        env:
          GROONGA_REPOSITORY: ../../../groonga
      - name: Build with Docker
        run: |
          cd packages/${{ matrix.package }}-mroonga
          case ${{ matrix.os }} in
            debian-*)
              rake apt:build APT_TARGETS=${{ matrix.os }}
              mv apt/repositories/ ../../
              ;;
            centos-*)
              rake yum:build YUM_TARGETS=${{ matrix.os }}
              mv yum/repositories/ ../../
              ;;
          esac
        env:
          GROONGA_REPOSITORY: ../../../groonga
      - uses: actions/upload-artifact@master
        with:
          name: packages-${{ matrix.package }}-${{ matrix.os }}
          path: repositories/
